apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps

resources:
  - deployment.yaml
  - service.yaml
  - env.yaml

configMapGenerator:
  - name: homeassistant-config
    files:
      - configuration.yaml=configs/configuration.yaml

